EmployeeManageProject/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>社員</label>
    <nameField>
        <label>社員名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>社員</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>社員コード</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/FanNickname__c.field-meta.xml
<CustomField>
    <fullName>FanNickname__c</fullName>
    <label>ファンの愛称</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>所属グループ</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>社員</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/HireDate__c.field-meta.xml
<CustomField>
    <fullName>HireDate__c</fullName>
    <label>入社日</label>
    <type>Date</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/ImageURL__c.field-meta.xml
<CustomField>
    <fullName>ImageURL__c</fullName>
    <label>画像URL</label>
    <type>Url</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/Kana__c.field-meta.xml
<CustomField>
    <fullName>Kana__c</fullName>
    <label>かな</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/RetirementDate__c.field-meta.xml
<CustomField>
    <fullName>RetirementDate__c</fullName>
    <label>退社日</label>
    <type>Date</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/YouTube__c.field-meta.xml
<CustomField>
    <fullName>YouTube__c</fullName>
    <label>YouTube</label>
    <type>Url</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>グループ</label>
    <nameField>
        <label>グループ名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>グループ</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EmployeeManageProject/force-app/main/default/objects/Group__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>コード</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Group__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <description>リストの並び順</description>
    <label>並び順</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

EmployeeManageProject/force-app/main/default/classes/EmployeeRepository.cls
// 本来はインターフェイスで定義し実装は別クラスで定義なのですが端折っております。許して
public inherited sharing class EmployeeRepository {

    private EmployeeConverter converter = new EmployeeConverter();

    public EmployeeRepository() {}

    public Employees getAll() {
        List<Employee__c> employeeList = [
            select 
                Id, Name, Code__c, FanNickname__c
                , Group__r.Id, Group__r.Name, Group__r.Code__c, Group__r.SortOrder__c
                , HireDate__c, ImageURL__c, Kana__c, RetirementDate__c, Twitter__c, YouTube__c
            from Employee__c 
            order by Code__c
            ];

        return converter.createEmployees(employeeList);
    }

    public void store(EmployeeDifferences differences) {
        
        List<Employee__c> insertList = new List<Employee__c>();
        List<Employee__c> updateList = new List<Employee__c>();
        List<Employee__c> deleteList = new List<Employee__c>();

        for(Iterator<EmployeeDifference> iterator = differences.Iterator(); iterator.hasNext();) {
            EmployeeDifference difference = iterator.next();
            if(difference.hasDifference()) {
                Employee__c employee = converter.createAfterEmployee(difference);
                if(difference.isNew()) {
                    insertList.add(employee);
                } else if(difference.isChange()){
                    updateList.add(employee);
                } else if(difference.isDeleted()){
                    deleteList.add(employee);
                }
            }
        }

        delete deleteList;
        update updateList;
        insert insertList;
    }
}