EmployeeManageProject/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>社員</label>
    <nameField>
        <label>社員名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>社員</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>社員コード</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/FanNickname__c.field-meta.xml
<CustomField>
    <fullName>FanNickname__c</fullName>
    <label>ファンの愛称</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>所属グループ</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>社員</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/HireDate__c.field-meta.xml
<CustomField>
    <fullName>HireDate__c</fullName>
    <label>入社日</label>
    <type>Date</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/ImageURL__c.field-meta.xml
<CustomField>
    <fullName>ImageURL__c</fullName>
    <label>画像URL</label>
    <type>Url</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/Kana__c.field-meta.xml
<CustomField>
    <fullName>Kana__c</fullName>
    <label>かな</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/RetirementDate__c.field-meta.xml
<CustomField>
    <fullName>RetirementDate__c</fullName>
    <label>退社日</label>
    <type>Date</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Employee__c/fields/YouTube__c.field-meta.xml
<CustomField>
    <fullName>YouTube__c</fullName>
    <label>YouTube</label>
    <type>Url</type>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>グループ</label>
    <nameField>
        <label>グループ名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>グループ</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EmployeeManageProject/force-app/main/default/objects/Group__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>コード</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

EmployeeManageProject/force-app/main/default/objects/Group__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <description>リストの並び順</description>
    <label>並び順</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

EmployeeManageProject/force-app/main/default/classes/EmployeeConverter.cls
public class EmployeeConverter {
    public EmployeeConverter() {
    }

    public Employees createEmployees(List<Employee__c> employeeList) {
        List<Employee> employees = new List<Employee>();
        for(Employee__c emp : employeeList) {
            GroupMaster belongGroup = new GroupMaster(
                emp.Group__r.Id, new GroupCode(emp.Group__r.Code__c), new GroupName(emp.Group__r.Name)
                , new GroupSortOrder(emp.Group__r.SortOrder__c.intValue())
            );
            employees.add(
                new Employee(
                    emp.Id, emp.Name, emp.Kana__c, emp.Code__c, emp.HireDate__c, emp.RetirementDate__c
                    , belongGroup, emp.ImageURL__c, emp.Twitter__c, emp.YouTube__c, emp.FanNickname__c
                )
            );
        }
        return new Employees(employees);
    }

    public Employee__c createAfterEmployee(EmployeeDifference difference) {

        if(!difference.hasDifference()) throw new IllegalArgumentException('差異がない');

        Employee__c emp;
        if(difference.isDeleted()){
            emp = new Employee__c(
                Id = difference.employee.id
            );
        } else {
            emp = new Employee__c(
                Name = difference.importEmployee.name
                , Kana__c = difference.importEmployee.kana
                , Code__c = difference.importEmployee.code
                , HireDate__c = difference.importEmployee.hireDate
                , RetirementDate__c = difference.importEmployee.retirementDate
                , Group__r = new Group__c(Code__c = difference.importEmployee.belongGroupCode)
                , ImageURL__c = difference.importEmployee.imageURL
                , Twitter__c = difference.importEmployee.twitterURL
                , YouTube__c = difference.importEmployee.youTubeURL
                , FanNickname__c = difference.importEmployee.fanNickname
            );
            if(difference.isChange()) {
                emp.Id = difference.employee.id;
            }
        }
        return emp;
    }
}